---
- hosts: compute:storage
  become: yes
  strategy: free
  gather_facts: no

  tasks:
  - name: "showpid group"
    group: name=showpid system=yes

  - name: "monitoring user"
    user: name=monitoring system=yes groups=showpid append=yes

  - name: 'supervisor install'
    apt: name=supervisor

  - name: "install prometheus compute python file"
    copy: src="files/prometheus_compute.py"
          dest="/home/monitoring/prometheus_compute.py"
          owner=monitoring group=monitoring mode=700

  - name: "install node_exporter"
    copy: src="files/node_exporter"
          dest="/home/monitoring/node_exporter"
          owner=monitoring group=monitoring mode=700

  - name: "install supervisor config"
    copy: src="files/prometheus-compute-supervisor.conf"
          dest="/etc/supervisor/conf.d/prometheus-compute.conf"

  - name: "restart daemons"
    supervisorctl: "name='prometheus:' state=restarted"


