# This is really a template for generating the yaml that describes the deployments
# for each of the storage nodes.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smc-project-{project_id}
  labels:
    run        : smc-project
    project_id : {project_id}
  annotations:
    deployment.kubernetes.io/revision: "1"
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/project
spec:
  replicas: 1
  selector:
    matchLabels:
      project_id : {project_id}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
          project_id : {project_id}
          run        : smc-project
    spec:
      containers:
      - name: project
        image: {image}
        imagePullPolicy: {pull_policy}
        volumeMounts:
        - name: no-api-access-please   # see https://github.com/kubernetes/kubernetes/issues/16779
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
        - name: project
          mountPath: /projects/{project_id}
        env:
          - name: SMC_PROJECT_ID
            value: {project_id}
          - name: SMC_SECRET_TOKEN
            value: {secret_token}
        resources: {resources}
      nodeSelector:
        preemptible: "{preemptible}"
      terminationGracePeriodSeconds: 1  # kill fast so can move, avoid multiple services on same files, etc.
      volumes:
      - name: no-api-access-please
        emptyDir: {}
      - name: project
        flexVolume:
          driver : "smc/smc-storage"
          options:
            namespace : {namespace}
            server    : "storage{storage_server}"
            path      : "projects/{project_id}.zfs"
            size      : {disk_size}
