apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    - name: test2
      mountPath: /data2
    - name: omnibase
      mountPath: /omnibase
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : 'storage-storage0:/projects'
        path   : "test.zfs"
        size   : "3000m"
  - name: test2
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : 'storage-storage1:/projects'
        path   : "test2.zfs"
        size   : "3000m"
  - name: omnibase
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : 'storage-storage0:/projects'
        path   : "369491f1-9b8a-431c-8cd0-150dd15f7b11.zfs"
        size   : "10000m"
  nodeSelector:
    volume: storage
